[DRAFT] NCR Loadout Renames & Adjustment
Afterglow-Ss13/afterglow-ss13 pull request #107
Opened 2023-06-16 19:50 UTC by AllCorruptingWyrm

## About The Pull Request
This PR has been made to tune down the NCR slots by at least 2 and bring them in line with the skill system. The PR also adds civilian rangers for the elite whitelist when that is implemented, it also formally adds the off-duty slot to the NCR base with stipulations as to what they can or can not do. Expect bugs and whacky stuff. All inbuilt traits/quirks have been demolished as well.

The following PR has ALSO been made with the blessings of Tef and co.

The map changes were because strongdmm updated to accommodate the armor PR.
There are going to be missing things I forgot to change, this is why it is a draft pr.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Civie Ranger
add: Off duty
add: camp doctor/logistician
tweak: conscripts at 4, troopers at 6
remove: 2 slots from NCR sergeant
remove: mo
remove: brahmin baron loadouts/rep loadouts
There is likely more, this is a draft.
/:cl:

2023-06-16 21:39 UTC, BadAtThisGame302 requested changes

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +	description = "You are the direct superior to the NCOs and Enlisted as well as the Rangers. You are the XO of Camp Blythe. You plan patrols, training and missions and in all circumstances, Rangers i
and missions and, grammar error

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/__DEFINES/jobs.dm
> +#define JOB_DISPLAY_ORDER_VETRANGE 51
VETRANGE... (R)?

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/* /datum/outfit/loadout/repbrahminbaron, */
Any reason why you remove these three Rep loadouts?

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/scoutleader, // Scout Carbine, Trekking
You're changing this to a Marksman Carbine.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/specialistleader, // Trench Shotgun, Gas mask, Smoke bombs, Trench knife
You're changing this to an Auto-5 and removing the gas mask, smoke bombs and trench knife.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +	supervisors = "NCRA Lieutenant"
Are you removing the Captain? Since you didn't change his slots I am confused.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/conscriptrancher // Varmint rifle, 9mm pistol, Sergeants and above get automatics!!! - Tzula
The rancher is getting an improvised caravan shotgun... not a varmint rifle or a 9mm pistol.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
>  		/obj/item/gun/ballistic/revolver/m29 = 1,
Forgot to remove this.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/obj/item/gun/ballistic/revolver/m29 = 1,
Forgot to change this to 10mm pistol?

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/thegroundpounder, //riot shotgun, 10mm n99
You're not giving this loadout a 10mm pistol.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/thepointman,	// assault carbine and .45 colt
You're not giving this loadout a .45 Colt.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/theserviceman,	// assault carbine and .45 colt
You're not giving this loadout a .45 Colt.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +	/datum/outfit/loadout/fobranger, // Lever shotgun, .45 Colt,
You're giving this loadout a .357 Revolver not a .45 Colt.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +	/datum/outfit/loadout/civilianranger, // Cowboy repeater, .45 Colt,
You're giving this loadout a .357 Revolver not a .45 Colt.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/corporalmarksman,		//  Hunting rifle w/ scope, 9mm pistol # Do not give them automatics
This loadout does not get a 9mm Pistol.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
>  		/obj/item/ammo_box/shotgun/buck = 2,
Forgot to remove this.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/troopermarksman, // Hunting rifle w/ 9mm pistol
This loadout does not get a 9mm Pistol.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/troopercorpsman, // M1/n carbine, Trench tool, Sandbags
This loadout does not get an M1/n carbine or a trench tool or sandbags.

2023-06-16 21:39 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/trooperengineer // Hunting shotgun, 9mm pistol, utility belt,
This loadout does not get a Hunting shotgun, 9mm pistol or utility belt.

2023-06-17 06:37 UTC, AllCorruptingWyrm commented
thank you for the comments, more work will be done on it, it obviously isn't perfect.

2023-06-17 10:49 UTC, BadAtThisGame302 commented
> thank you for the comments, more work will be done on it, it obviously isn't perfect.

I was just bored and reviewed it, hit me up on discord if you need help/have any problems.

2023-06-21 03:41 UTC, AllCorruptingWyrm commented
Closing this as Rebel copied my code; I'm way too burnt out to get this to work.

2023-06-21 03:41 UTC, closed without merging