Role Name Fixes + Removes OP Ammo
Afterglow-Ss13/afterglow-ss13 pull request #34
Opened 2023-06-02 02:02 UTC by Stutternov

## About The Pull Request
Tl;dr - Removes OP ammo types like contamination rounds and electroshock.
Also does what Myrios asked for with Legion Immunes and Legion role-names.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
removes: OP as shit ammo types.
tweaks: Edits role names to align with what was asked for.
/:cl:

2023-06-02 08:28 UTC, Zero-Percent-Angel commented
Can you fix the old maps by getting rid of the old types so that the pipeline doesn't complain?

2023-06-02 08:32 UTC, Zero-Percent-Angel commented
Also, check the start landmarks, otherwise all the jobs you've changed the title of will spawn in nowhere.
And can you check the Jobs.dm as well these values will need updating:
![image](https://github.com/Afterglow-Ss13/afterglow-ss13/assets/119936892/7f5baf6b-35d4-426d-a3dd-6056a5c87aa5)
Otherwise they won't even show up in the menu to pick them.

2023-06-02 08:33 UTC, Zero-Percent-Angel requested changes
Check my comments for some suggestions :)

2023-06-02 15:18 UTC, panzerr1944 commented
Dont forget to obliterate .50 MG Rubber

2023-06-02 19:36 UTC, Stutternov commented
> 

I didn't change the paths so it should be fine for spawning. Example currently is that /obj/effect/landmark/start/f13/slave is assigned the name "Camp Follower" but path is still code-wise slave and called as code-wise slave.  Can change it but I'd suggest not to personally UNLESS the map is going to get edited at the same time. (I'm avoiding map edits on my end for now to avoid conflicts with any other map PRs.)

2023-06-02 19:55 UTC, Stutternov commented
Fixed the map conflicts.

2023-06-02 21:46 UTC, Zero-Percent-Angel commented
> > 
> 
> I didn't change the paths so it should be fine for spawning. Example currently is that /obj/effect/landmark/start/f13/slave is assigned the name "Camp Follower" but path is still code-wise slave and called as code-wise slave. Can change it but I'd suggest not to personally UNLESS the map is going to get edited at the same time. (I'm avoiding map edits on my end for now to avoid conflicts with any other map PRs.)
> 
> Whitelist thing will probably need to be changed though, I'll push that now.

We don't actually have the slave role enabled, which is why I renamed it to camp follower otherwise you ended up on the main menu screen

2023-06-02 22:50 UTC, Zero-Percent-Angel commented on code/modules/jobs/jobs.dm
>  	"Prime Legionnaire",
need to change it here as well otherwise it won't show up in the spawn menu, currently you can't spawn in on these roles now.

2023-06-02 22:51 UTC, Zero-Percent-Angel commented on code/modules/jobs/jobs.dm
>  	"Prime Legionnaire",
![image](https://github.com/Afterglow-Ss13/afterglow-ss13/assets/119936892/385c3d1a-95ae-4f0f-9d09-59c9d2e40259)

2023-06-03 19:42 UTC, Zero-Percent-Angel approved these changes
Okay, I'll pop this into the dev branch and have a look at it with a few other things, we'll see about getting it deployed soonish

2023-06-03 20:39 UTC, merged